services:
  database:
    image: postgres
    container_name: ait-manager
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ait-manager
    volumes:
      - pgdata:/data/postgres

  localstack:
    image: localstack/localstack:3.8
    container_name: ait-manager-localstack
    restart: always
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d

volumes:
  pgdata:
    driver: local
